### ISSUE TITLE
have no filter isoform gtf files

### ISSUE THREAD

**Issue by JXAUDZF** [christopher-vollmers/Mandalorion#2]
![a](https://github.com/christopher-vollmers/Mandalorion/assets/115453641/f657b590-feef-4b83-989a-d0d025ffe2f1)
-M APDF the result files only have a part of them.

**Comment by JXAUDZF** [comment]
<img width="1185" alt="image" src="https://github.com/christopher-vollmers/Mandalorion/assets/115453641/a98b6f2c-b5ac-4711-ab1e-6d3fc98a9a43">
install abPOA failed.

**Comment by christopher-vollmers** [comment]
Hi,

When did you pull your Mandalorion version? I just did some updates over the weekend and it would be helpful to know. 

There might be multiple issues. It seems like the P module isn't running properly because you don't get your files converted to psl. Could you send the terminal messages from running just the -M P so I can figure out what is going on here?

The second issue is the abpoa installation. I'm not an expert on abpoa. We just pull and use it. But from quickly googling the error, it seems to be an issue with the compiler. You could either update gcc and try again or add 

CFLAGS=-std=c99 

to the make file and try again. If we can't figure this out, I'm sure the abpoa people can help. 

Best,
Chris

**Comment by JXAUDZF** [comment]
<img width="1006" alt="image" src="https://github.com/christopher-vollmers/Mandalorion/assets/115453641/5647194f-469f-4fa3-adc4-78b842b1da2e">
and the software abPOA is installed fail contribute to the results,I don't know how to make successfully.

**Comment by JXAUDZF** [comment]
have been soluted.Thank you.

**Comment by JXAUDZF** [comment]
<img width="592" alt="image" src="https://github.com/christopher-vollmers/Mandalorion/assets/115453641/e8805ef6-fd4e-4b52-8244-5ca850eed026">
have no gif file

**Comment by JXAUDZF** [comment]
<img width="894" alt="image" src="https://github.com/christopher-vollmers/Mandalorion/assets/115453641/e9d32d69-41ee-4240-92a3-b18b08eec136">
seem  P mole is error

**Comment by JXAUDZF** [comment]
Thanks for soluting the questions!

**Comment by christopher-vollmers** [comment]
Hi,

the error in P is just a warning. I does break anything so it should be fine.

Do you still have no gtf? It's not clear right now where things are breaking or if they are still breaking.

Best,
Chris

**Comment by JXAUDZF** [comment]
have succeeded, thank you very much.
